Repository CSC59939/Rails, pull requests merged in 2018-12, with the labels that each got.

#92 Tests on IconButton Component
  website/src/components/IconButton/IconButton.test.jsx
Labels: Normal, needs-review

#91 More test for ProfileInfo, Notification and NotFound page
  website/src/components/Notification/Notification.test.jsx
  website/src/components/ProfileInfo/ProfileInfo.test.jsx
  website/src/views/NotFound/NotFound.test.jsx
Labels: Normal

#90 snapshot tests and enzyme tests on profile page
  website/src/views/Profile/Profile.test.jsx
  website/src/views/Profile/__snapshots__/Profile.test.jsx.snap
Labels: Critical, needs-review

#94 Ka shing page test
  website/src/views/JoinClass/JoinClass.test.jsx
  website/src/views/Signin/Signin.jsx
Labels: Normal, needs-review

#95 Updated and added new APIs
  .gitignore
  functions/package-lock.json
  functions/src/handlers/AddMessageHandler.ts
  functions/src/handlers/CreateEventHandler.ts
  functions/src/handlers/DropClassHandler.ts
  functions/src/handlers/EditClassHandler.ts
  functions/src/handlers/EditEventHandler.ts
  functions/src/handlers/GetClassDetailHandler.ts
  functions/src/handlers/GetClassesHandler.ts
  functions/src/handlers/GetEventDetailHandler.ts
  functions/src/handlers/GetProfileHandler.ts
  functions/src/handlers/index.ts
  functions/src/index.ts
  website/package-lock.json
  website/src/SampleBackEndTest/SampleTest.js
  website/src/SampleBackEndTest/SampleTest.test.js
  website/src/views/JoinClass/JoinClass.jsx
Labels: Critical, needs-review

#97 Create Event UI
  website/package-lock.json
  website/src/components/CreateEventDrawer/CreateEventDrawer.css
  website/src/components/CreateEventDrawer/CreateEventDrawer.jsx
  website/src/components/CreateEventDrawer/CreateEventDrawer.test.jsx
  website/src/components/DashboardHeader/DashboardHeader.jsx
  website/src/components/DashboardHeader/__snapshots__/DashboardHeader.test.jsx.snap
  website/src/components/HeaderIcons/HeaderIcons.css
  website/src/components/Notification/Notification.jsx
  website/src/components/index.js
  website/src/views/DashboardRouter/DashboardRouter.jsx
  website/src/views/DashboardRouter/__snapshots__/DashboardRouter.test.jsx.snap
  website/src/views/Profile/Profile.css
  website/src/views/Profile/Profile.jsx
  website/src/views/Profile/__snapshots__/Profile.test.jsx.snap
Labels: Normal, needs-review

#98 API
  functions/src/handlers/CreateEventHandler.ts
  functions/src/handlers/EditEventHandler.ts
  functions/src/handlers/GetEventDetailHandler.ts
Labels: Normal, needs-review

#100 service worker
  .travis.yml
  service-worker.json
  website/package.json
  website/src/index.js
  website/src/serviceWorker.js
  website/src/views/DashboardRouter/DashboardRouter.jsx
  website/workbox-config.js
Labels: Normal, needs-review

#99 Big Calendar agenda
  website/package-lock.json
  website/package.json
  website/src/components/EventCalendar/EventCalendar.css
  website/src/components/EventCalendar/EventCalendar.jsx
  website/src/components/EventCalendar/EventCalendar.test.jsx
  website/src/components/EventCalendar/__snapshots__/EventCalendar.test.jsx.snap
  website/src/components/EventSummary/EventSummary.css
  website/src/components/EventSummary/EventSummary.jsx
  website/src/components/EventSummary/EventSummary.test.jsx
  website/src/components/EventSummary/__snapshots__/EventSummary.test.jsx.snap
  website/src/components/EventSummaryCollection/EventSummaryCollection.css
  website/src/components/EventSummaryCollection/EventSummaryCollection.jsx
  website/src/components/EventSummaryCollection/EventSummaryCollection.test.jsx
  website/src/components/EventSummaryCollection/__snapshots__/EventSummaryCollection.test.jsx.snap
  website/src/components/index.js
  website/src/views/DashboardHome/DashboardHome.jsx
  website/src/views/DashboardHome/__snapshots__/DashboardHome.test.jsx.snap
  website/src/views/DashboardRouter/DashboardRouter.jsx
  website/src/views/Home/Home.test.jsx
Labels: Critical

#102 Responsive nav
  website/src/components/EventCalendar/EventCalendar.css
  website/src/components/ProfileInfo/ProfileInfo.css
Labels: Normal

#101 Edit Class
  functions/src/handlers/CreateClassHandler.ts
  website/src/App.jsx
  website/src/Router.test.jsx
  website/src/views/CreateClass/CreateClass.jsx
  website/src/views/CreateClass/__snapshots__/CreateClass.test.jsx.snap
  website/src/views/Profile/Profile.jsx
  website/src/views/Profile/Profile.test.jsx
  website/src/views/Profile/__snapshots__/Profile.test.jsx.snap
  website/src/views/Signup/Signup.jsx
Labels: Critical, needs-review

#106 Tobias test
  backup-server/watcher/package-lock.json
  backup-server/watcher/src/App.js
  website/package-lock.json
  website/src/App.jsx
  website/src/components/DashboardHeader/DashboardHeader.test.jsx
  website/src/components/DashboardHeader/__snapshots__/DashboardHeader.test.jsx.snap
  website/src/components/EventSummary/EventSummary.jsx
  website/src/components/EventSummary/EventSummary.test.jsx
  website/src/components/HeaderIcons/HeaderIcons.jsx
  website/src/components/HeaderIcons/HeaderIcons.test.jsx
  website/src/views/DashboardRouter/DashboardRouter.test.jsx
Labels: Normal, needs-review

#105 Api testing
  website/src/APITesting/GetClassApi.test.js
  website/src/APITesting/GetClassDetails.test.js
  website/src/APITesting/GetEventDetails.test.js
  website/src/APITesting/RequestApi.test.js
  website/src/APITesting/SignupAPi.test.js
Labels: Critical, needs-review
