Repository CSC59939/Rails, pull requests merged in 2018-11, with the labels that each got.

#41 Protected route
  firebase.json
  website/package-lock.json
  website/src/App.css
  website/src/App.jsx
  website/src/components/DashboardHeader/DashboardHeader.jsx
  website/src/components/DashboardHeader/DisplayHeader.css
  website/src/components/Delayed/Delayed.jsx
  website/src/components/index.js
  website/src/hoc/WithProtectedView/WithProtectedView.jsx
  website/src/hoc/firebase/firebase.jsx
  website/src/hoc/index.js
  website/src/index.js
  website/src/views/CreateClass/CreateClass.jsx
  website/src/views/DashboardRouter/DashboardRouter.jsx
  website/src/views/JoinClass/JoinClass.jsx
  website/src/views/Signin/Signin.jsx
  website/src/views/index.js
Labels: Critical, needs-review

#44 APIs
  functions/API_DOCS.md
  functions/Handlers/ApproveClassHandler.js
  functions/Handlers/CreateClassHandler.js
  functions/Handlers/GetClassesHandler.js
  functions/Handlers/JoinClassHandler.js
  functions/Handlers/RequestClassHandler.js
  functions/Handlers/SignupHandler.js
  functions/Handlers/index.js
  functions/index.js
  functions/package-lock.json
  functions/package.json
Labels: Critical, needs-review

#46 Signin fix
  website/package-lock.json
  website/src/views/Signin/Signin.jsx
  website/src/views/Signup/Signup.jsx
Labels: Normal

#49 Resolve all syntax errors
  website/src/components/Dashboard/Dashboard.jsx
  website/src/components/Delayed/Delayed.jsx
  website/src/components/HeaderIcons/HeaderIcons.jsx
  website/src/components/index.js
  website/src/views/JoinClass/JoinClass.jsx
  website/src/views/Signup/Signup.jsx
Labels: Normal

#47 Get Profile User API
  firebase.json
  functions/.eslintrc.json
  functions/.gitignore
  functions/API_DOCS.md
  functions/Handlers/index.js
  functions/index.js
  functions/package-lock.json
  functions/package.json
  functions/src/handlers/ApproveClassHandler.ts
  functions/src/handlers/CreateClassHandler.ts
  functions/src/handlers/GetClassesHandler.ts
  functions/src/handlers/GetProfileHandler.ts
  functions/src/handlers/JoinClassHandler.ts
  functions/src/handlers/RequestClassHandler.ts
  functions/src/handlers/SignupHandler.ts
  functions/src/handlers/index.ts
  functions/src/index.ts
  functions/src/typings.d.ts
  functions/tsconfig.json
  functions/tslint.json
Labels: Critical, needs-review

#73 Major UI Additions, Changes & Fixes
  functions/src/handlers/GetClassesHandler.ts
  website/package-lock.json
  website/package.json
  website/src/App.css
  website/src/views/CreateClass/CreateClass.css
  website/src/views/CreateClass/CreateClass.jsx
  website/src/views/JoinClass/JoinClass.css
  website/src/views/JoinClass/JoinClass.jsx
  website/src/views/Profile/Profile.css
  website/src/views/Profile/Profile.jsx
Labels: Critical, needs-review

#77 added password strength indicator
  website/public/password-lock.png
  website/src/views/Signin/Signin.jsx
  website/src/views/Signup/Signup.css
  website/src/views/Signup/Signup.jsx
Labels: Normal, needs-review

#79 add forgot password
  website/src/views/Signin/Signin.css
  website/src/views/Signin/Signin.jsx
Labels: Normal, needs-review

#82 Minor Fixes in Website
  website/.stylelintignore
  website/public/index.html
  website/public/logo.png
  website/public/logo.svg
  website/public/password-lock.png
  website/src/components/DashboardHeader/DashboardHeader.jsx
  website/src/components/DashboardHeader/__snapshots__/DashboardHeader.test.jsx.snap
  website/src/components/ProfileInfo/ProfileInfo.css
  website/src/components/ProfileInfo/ProfileInfo.jsx
  website/src/resources/logo.svg
  website/src/views/DashboardRouter/DashboardRouter.jsx
  website/src/views/Profile/Profile.css
  website/src/views/Profile/Profile.jsx
  website/src/views/Profile/__snapshots__/Profile.test.jsx.snap
Labels: Critical, needs-review

#83 Fixed Pre-approved email modal dialog
  website/src/views/JoinClass/JoinClass.jsx
Labels: Normal

#86 Snap shot fix (Cont'd from SnapShot #80)
  website/src/components/EventSummary/EventSummary.test.jsx
  website/src/components/EventSummary/__snapshots__/EventSummary.test.jsx.snap
  website/src/components/EventSummaryCollection/EventSummaryCollection.test.jsx
  website/src/components/EventSummaryCollection/__snapshots__/EventSummaryCollection.test.jsx.snap
  website/src/components/HeaderIcons/HeaderIcons.test.jsx
  website/src/components/HeaderIcons/__snapshots__/HeaderIcons.test.jsx.snap
  website/src/components/IconButton/IconButton.test.jsx
  website/src/components/MaterialIcon/MaterialIcon.test.jsx
  website/src/components/ProfileInfo/ProfileInfo.test.jsx
  website/src/components/ProfileInfo/__snapshots__/ProfileInfo.test.jsx.snap
  website/src/views/CreateClass/CreateClass.test.jsx
  website/src/views/CreateClass/__snapshots__/CreateClass.test.jsx.snap
  website/src/views/DashboardHome/DashboardHome.test.jsx
  website/src/views/DashboardHome/__snapshots__/DashboardHome.test.jsx.snap
  website/src/views/DashboardRouter/DashboardRouter.test.jsx
  website/src/views/DashboardRouter/__snapshots__/DashboardRouter.test.jsx.snap
  website/src/views/Home/Home.test.js
  website/src/views/Home/Home.test.jsx
  website/src/views/Home/__snapshots__/Home.test.jsx.snap
  website/src/views/JoinClass/JoinClass.test.jsx
  website/src/views/JoinClass/__snapshots__/JoinClass.test.jsx.snap
  website/src/views/Profile/Profile.test.jsx
  website/src/views/Profile/Profiletest.js
  website/src/views/Signin/Signin.test.jsx
  website/src/views/Signin/__snapshots__/Signin.test.jsx.snap
Labels: Normal, needs-review

#87 enzyme shallow
  website/src/views/Home/Home.test.jsx
Labels: needs-review

#88 enzyme testing on sign in page
  website/src/views/Signin/Signin.test.jsx
Labels: Normal, needs-review
